loadbalancer_id     = "lbid"
name                = "probenamehere"
port                = "433"
protocol            = "TCP"
probe_threshold     = "30"
request_path        = "/"
interval_in_seconds = "5"
number_of_probes    = "2"